---
title: "ECYP Fellows and Alumni Database"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("tidyverse")
# install.packages("tidyr")
# install.packages("flexdashboard")
# install.packages('DT')
# install.packages("gsheet")

library(dplyr)
library(readr)
library(gsheet)
library(tidyverse)
library(ggplot2)
library(datasets)
library(data.table)
library(gsheet)
library(shiny)
library(DT)
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
textInput("enter_number", label = h3("Enter your number"), value = "", placeholder = NULL)
```

```{r}
Masterfile <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1rQaqQIYLZw1tZnJZQHMNhTf0-zDRH2zWzA6Eo0giP80/edit#gid=1665986408')

#Delete a column

Masterfile <- Masterfile[ -c(2)]

#change column
names(Masterfile) [1] <- "Class Year"
names(Masterfile) [2] <- "Unique_Number"
names(Masterfile) [3] <- "Full Name"
names(Masterfile) [4] <- "Address"
names(Masterfile) [5] <- "City State Zip"
names(Masterfile) [7] <- "Permanent Telephone"
names(Masterfile) [8] <- "Email"
names(Masterfile) [9] <- "High School"
names(Masterfile) [10] <- "Hc Grad Year"
names(Masterfile) [11] <- "College Post Grad School"
names(Masterfile) [12] <- "Grad Year"
names(Masterfile) [13] <- "Degree Major"
names(Masterfile) [14] <- "Last Updated"
names(Masterfile) [15] <- "Grad School"
names(Masterfile) [16] <- "Grad School Year"
names(Masterfile) [17] <- "LinkedIN"
names(Masterfile) [18] <- "Notes"
names(Masterfile) [19] <- "Employers"

variable_list <- names(Masterfile)[-2]
names(variable_list) <- paste("Enter", names(Masterfile)[-2])

```

## Column

```{r}
# palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
#   "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

renderTable({
  dplyr::filter(Masterfile, Unique_Number == input$enter_number)
  
})
```

```{r}
selectInput("variable", "Choose which field to update Info:", colnames(Masterfile)[-2])

renderUI({
  field_text <- names(variable_list)[[which(variable_list == input$variable)]]
  textInput(paste0("new_", input$variable), field_text)
})
```


```{r}
```
